{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iag5.serviceAccountName" . }}
  labels:
    {{- include "iag5.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceAccount
  annotations:
    kubernetes.io/description: "Itential Automation Gateway 5 serviceAccount."
    {{- include "iag5.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
